language: node_js
node_js:
- '6'
install:
- npm install && npm install @deskproapps/dpat@0.4.12
script:
- npm run package
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: g/oMi1i3Bem+UY7Y2R/4M9Y4DxS0hzYY9LmhixQBGtx5hh6taEXEqecQBjY/bbXivmf65RaANSWoml/O4dTBtOnyFg22kQ0vSKX1GBf+7h7vntD/e55pLQIPJ3rYmzta6Hsv1WkHgh7XsxlCA7zv/v4hJhZh+gf8yGiZP/xvj2NLDh+7wOvHDCo4ss/Ung2OfqSWUy7MvlOD2JzoelKwxS/WhHIMjzGqkKuXnjkJ0sJNdFBB59GU7UTJlA58UJLlffdQyG0KUHh7J21nqHV+sXihxZa5JOanHeaTB0y9NtsKY85jTiucKnAK7ND3IIagH1T3v9PORSu3Drb1moUsUJaCKp68Blzw55bD/0ScNXl5hRidJIc3jw9Km6jdMit1Mb1wvUwyrBpol+UL3vcpA2Nq7fiAUjH/7f+t1zoUgabu3AR+zP2RblZyq8NtwUtrZ0E2wx2YPIu4tUvhTCChyDnXGXNLUdpG06fogZ0/5ZP05Kigh2YGOfl0tn3vSmWc66gIM0N98V5o2gumvi3k5jggkUAkeuB/Novbzs/urqgvLQf3nwA9YIy1HSY46YDLm9Aa6LltpU21Gy8DwMBDvPTVQvFLQ6p8Q6LkLKkRFi0lRkBoPyxzvxbOLDmQqu1EkUcxkM0FUmjKVKPo+hWdx/nW6qjNYXg4fLPD+fzU1u8=
  file: dist/app.zip
  on:
    repo: DeskproApps/labs-manipulate-dom
    tags: true